os:
- linux

sudo: required
env:
  global:
    - ANDROID_API_LEVEL=28
    - EMULATOR_API_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ADB_INSTALL_TIMEOUT=20 # minutes
    - ANDROID_TAG=google_apis
    - ANDROID_ABI=armeabi-v7a
    - QEMU_AUDIO_DRV=none

before_install:
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm --version
  - node --version
  - npx --version
  - export ANDROID_HOME=/usr/local/android-sdk
  - export PATH=$PATH:$ANDROID_HOME/emulator
  - export PATH=$PATH:$ANDROID_HOME/tools
  - export PATH=$PATH:$ANDROID_HOME/tools/bin
  - export PATH=$PATH:$ANDROID_HOME/platform-tools

install:
  - npm install

language: android
jdk:
  - oraclejdk8

dist: trusty

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$EMULATOR_API_LEVEL
  - android-23
  - android-27
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-$ANDROID_ABI-$ANDROID_TAG-$ANDROID_API_LEVEL
  - sys-img-$ANDROID_ABI-$ANDROID_TAG-$EMULATOR_API_LEVEL
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - npx jetify
  - adb shell input keyevent 82 &


script:
  - cd android && sudo chmod +x gradlew && sudo ./gradlew clean && sudo ./gradlew assemble
  - cd ..
